import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import path from 'node:path'

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./tests/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: [
        'src/api/client.ts',
        'src/hooks/useI18n.ts',
        'src/i18n/**',
        'src/lib/**',
        'src/stores/authStore.ts',
        'src/routes/backup/**',
        'src/routes/disk-analysis/**',
        'src/routes/files/**',
        'src/routes/security-scan/**',
        'src/routes/ssl/**',
        'src/routes/ftp/**',
        'src/routes/operation-log/**',
        'src/routes/settings/**',
        'src/routes/cron/**',
        'src/routes/custom-error-pages/**',
        'src/routes/notifications/**',
        'src/routes/htaccess/**',
        'src/routes/system/**',
        'src/routes/dashboard/**',
        'src/routes/website-monitor/**',
        'src/routes/deploy/**',
        'src/routes/users/**',
        'src/routes/composer/**',
        'src/routes/devices/**',
        'src/routes/env-check/**',
        'src/routes/error-log/**',
        'src/routes/groups/**',
        'src/routes/health-check/**',
        'src/routes/invite-accept/**',
        'src/routes/invitations/**',
        'src/routes/login/**',
        'src/routes/notification-preferences/**',
        'src/routes/api-tokens/**',
        'src/routes/approvals/**',
        'src/routes/profile/**',
        'src/routes/sessions/**',
        'src/routes/tokens/**',
        'src/routes/upgrade/**',
        'src/routes/install/**',
        'src/routes/not-found/**',
        'src/routes/php-bench/**',
        'src/routes/php-errors/**',
        'src/routes/php-extensions/**',
        'src/routes/php-fpm/**',
        'src/routes/php-info/**',
        'src/routes/php-ini/**',
        'src/routes/php-opcache/**',
        'src/routes/php-processes/**',
        'src/routes/php-upgrade/**',
        'src/routes/status-page/**',
        'src/routes/user-activity/**',
        'src/routes/web-shell/**',
        'shared/version.ts',
      ],
      exclude: [
        'node_modules/',
        'dist/',
        'coverage/',
        'tests/',
        'src/**/*.test.ts',
        'src/**/*.test.tsx',
        'src/**/*.spec.ts',
        'src/**/*.spec.tsx',
      ],
      thresholds: {
        statements: 70,
        branches: 70,
        functions: 70,
        lines: 70,
        'src/api/client.ts': {
          statements: 70,
          branches: 70,
          functions: 70,
          lines: 70,
        },
        'src/components/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/hooks/useI18n.ts': {
          statements: 70,
          branches: 70,
          functions: 70,
          lines: 70,
        },
        'src/i18n/**': {
          statements: 70,
          branches: 70,
          functions: 70,
          lines: 70,
        },
        'src/lib/**': {
          statements: 70,
          branches: 70,
          functions: 70,
          lines: 70,
        },
        'src/stores/authStore.ts': {
          statements: 70,
          branches: 70,
          functions: 70,
          lines: 70,
        },
        'shared/version.ts': {
          statements: 70,
          branches: 70,
          functions: 70,
          lines: 70,
        },
        'src/routes/backup/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/disk-analysis/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/files/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/security-scan/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/ssl/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/ftp/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/operation-log/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/settings/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/cron/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/custom-error-pages/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/notifications/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/htaccess/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/system/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/dashboard/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/website-monitor/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/deploy/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/users/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/composer/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/devices/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/env-check/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/error-log/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/groups/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/health-check/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/invite-accept/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/invitations/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/login/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/notification-preferences/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/api-tokens/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/approvals/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/profile/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/sessions/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/tokens/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/upgrade/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/install/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/not-found/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/php-bench/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/php-errors/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/php-extensions/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/php-fpm/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/php-info/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/php-ini/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/php-opcache/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/php-processes/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/php-upgrade/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/status-page/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/user-activity/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
        'src/routes/web-shell/**': {
          statements: 0,
          branches: 0,
          functions: 0,
          lines: 0,
        },
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@shared': path.resolve(__dirname, './shared'),
    },
  },
})
